language: ruby
sudo: false
install: bundle install --without development --jobs=3 --retry=3
cache: bundler
env:
  global:
    - SITE_ENV=deploy
before_script:
- git config --global user.email "antondavyodv.o@gmail.com"
- git config --global user.name "Anton Davydov"
- git remote rm origin
- git remote add origin https://davydovanton:${GH_TOKEN}@github.com/hanami/hanami.github.io.git
- mkdir build
script:
- bundle exec bin/brokenurl
- if [ "$TRAVIS_BRANCH" = "build" ]; then ./bin/site build && bundle exec middleman deploy; fi
