source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-blog'
gem 'middleman-syntax'
gem 'middleman-deploy', '2.0.0.pre.alpha'
gem 'middleman-breadcrumbs'
gem 'redcarpet'
gem 'httparty'
gem 'nokogiri'
