* CHANGES
* README
* MANIFEST
* Rakefile
* ptools.gemspec
* certs/djberg96_pub.pem
* lib/ptools.rb
* test/test_constants.rb
* test/test_head.rb
* test/test_image.rb
* test/test_nlconvert.rb
* test/test_null.rb
* test/test_tail.rb
* test/test_touch.rb
* test/test_wc.rb
* test/test_which.rb
* test/test_whereis.rb
* test/img/test.gif
* test/img/test.jpg
* test/img/test.png
